FROM node:17-alpine

WORKDIR /usr/src/frontend

COPY . .
# Copy .eslintrc and other dotfiles.
COPY .* ./
ENV DISABLE_ESLINT_PLUGIN "true"
RUN npm install
RUN npm run build

ENV NODE_ENV "production"

WORKDIR /usr/src/frontend/build
RUN npm install serve -g
EXPOSE 3000
CMD ["serve", "-l", "3000"]