FROM node:17-alpine as build

WORKDIR /usr/src/backend
COPY package*.json ./
COPY tsconfig*.json ./
RUN npm ci
COPY . .
COPY .env .
RUN npm install -g typescript pm2
RUN npm run build
EXPOSE 4000

CMD ["pm2-runtime","build/src/api.js"]
