# Use this base image for OpenGL support inside a Docker container
FROM utensils/opengl:stable

# Setup dependencies
RUN apk add --no-cache git gource ffmpeg aws-cli npm

# Compile and run code
WORKDIR /worker/
ADD package*.json /worker/
ADD tsconfig*.json /worker/
RUN npm install typescript -g
RUN npm install
COPY .env /worker
COPY . /worker
RUN chmod +x /worker/src/render/gource.sh
RUN npm run compile

# CMD [ "node", "/worker/build/src/index.js" ]
CMD ["sleep", "1000000000"]