# Use this base image for OpenGL support inside a Docker container
FROM utensils/opengl:stable

# Setup dependencies
RUN apk add --no-cache git gource ffmpeg aws-cli npm

# Compile and run code
WORKDIR /worker/
COPY . .
RUN npm install typescript -g
RUN npm install
RUN chmod +x /worker/src/render/gource.sh
RUN npm run compile

CMD [ "node", "/worker/build/src/index.js" ]